kind: policy
name: default

service_account: drone-runner
---
kind: pipeline
type: kubernetes
name: espogmailsync-deploy

triggers:
 branch:
 - mater

steps:
- name: Build with Gradle
  image: openjdk:11
  commands:
  - chmod +x gradlew
  - ./gradlew shadowjar

- name: Build Docker container
  image: plugins/docker
  settings:
    repo: registry.thedutchmc.nl/espogmailsync-api
    tags:
    - latest
    registry: registry.thedutchmc.nl

- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl set image deployment/espogmailsync-deployment espogmailsync-api=registry.thedutchmc.nl/espogmailsync-api:latest
