kind: pipeline
type: kubernetes
name: drone-runner

triggers:
 branch:
 - mater

steps:
- name: Build with Gradle
  image: openjdk:11
  commands:
  - chmod +x gradlew
  - ./gradlew shadowjar

- name: Build Docker container
  image: plugins/docker
  settings:
    repo: registry.thedutchmc.nl/espogmailsync-api
    tags:
    - latest
    registry: registry.thedutchmc.nl
